/* =========================================================
   AIChat — Retrieval-Augmented Q&A over the electrical
   construction systematic review.

   Architecture:
     1. Load pre-computed paper embeddings from
        paper_embeddings.json (generated by compute_embeddings.py).
     2. On submit, embed the user's question with Gemini
        Embedding 001 and cosine-rank all 129 papers.
     3. Split top-12 into three tiers:
          cited     (top 3)  — full context, LLM must cite these
          mentioned (next 4) — compact context, optional citation
          further   (next 5) — shown in UI only, not sent to LLM
     4. Send cited + mentioned context to Gemini 2.5 Flash.
     5. Render answer with clickable citation chips that open
        the PaperDetail modal.

   Props
     rows        normalised paper records from data.csv
     workerBase  Cloudflare Worker URL (production)
     apiKey      Gemini API key (local dev only)
     onPaperClick  (paper) => void  — open detail modal
   ========================================================= */

window.AppCharts = window.AppCharts || {};

(function () {
  const { useState, useEffect, useRef, useMemo } = React;

  // ── API endpoints ─────────────────────────────────────
  const GEMINI_EMBED_URL    = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-embedding-001:embedContent';
  const GEMINI_GENERATE_URL = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent';

  // Retrieval tiers
  const CITED_K    = 3;
  const MENTIONED_K = 4;
  const FURTHER_K  = 5;
  const TOP_K      = CITED_K + MENTIONED_K + FURTHER_K; // 12

  // ── Cosine similarity ─────────────────────────────────
  const cosineSim = (a, b) => {
    let dot = 0, na = 0, nb = 0;
    for (let i = 0; i < a.length; i++) {
      dot += a[i] * b[i]; na += a[i] * a[i]; nb += b[i] * b[i];
    }
    return na === 0 || nb === 0 ? 0 : dot / (Math.sqrt(na) * Math.sqrt(nb));
  };

  // ── Embed a question ──────────────────────────────────
  const embedQuestion = async (workerBase, apiKey, text) => {
    const url = workerBase
      ? `${workerBase}/api/embed`
      : `${GEMINI_EMBED_URL}?key=${encodeURIComponent(apiKey)}`;
    const res = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        content: { parts: [{ text }] },
        taskType: 'RETRIEVAL_QUERY',
        outputDimensionality: 768,
      }),
    });
    if (!res.ok) {
      const t = await res.text();
      throw new Error(`Embedding error (${res.status}): ${t.slice(0, 200)}`);
    }
    const data = await res.json();
    return data?.embedding?.values ?? data?.embeddings?.[0]?.values;
  };

  // ── Generate answer ───────────────────────────────────
  const askGemini = async (workerBase, apiKey, question, cited, mentioned, history) => {
    // Full context for primary sources
    const citedBlock = cited.map((p, i) => {
      const s = p.summary || {};
      return [
        `[${i + 1}] ${p.citation}`,
        s.title           ? `  Title: ${s.title}` : null,
        s.abstract        ? `  Abstract: ${s.abstract}` : null,
        s.maturity        ? `  Maturity: ${s.maturity}` : null,
        s.ai_technique    ? `  AI Technique: ${s.ai_technique}` : null,
        s.digital_technology ? `  Digital Technology: ${s.digital_technology}` : null,
        s.construction_phase ? `  Construction Phase: ${s.construction_phase}` : null,
        s.electrical_scope   ? `  Electrical Scope: ${s.electrical_scope}` : null,
        s.pain_point      ? `  Pain Point Addressed: ${s.pain_point}` : null,
      ].filter(Boolean).join('\n');
    }).join('\n\n');

    // Compact context for supporting sources
    const mentionedBlock = mentioned.map((p, i) => {
      const s = p.summary || {};
      const idx = cited.length + i + 1;
      return [
        `[${idx}] ${p.citation}`,
        s.title        ? `  Title: ${s.title}` : null,
        s.maturity     ? `  Maturity: ${s.maturity}` : null,
        s.ai_technique ? `  AI Technique: ${s.ai_technique}` : null,
        s.abstract     ? `  Abstract: ${s.abstract.slice(0, 220)}${s.abstract.length > 220 ? '…' : ''}` : null,
      ].filter(Boolean).join('\n');
    }).join('\n\n');

    const systemCtx = `You are a research assistant for a systematic review of AI and digital technologies in electrical construction (129 peer-reviewed studies, 2008–2026).

The review covers how AI techniques (machine learning, computer vision, NLP, etc.) and digital technologies (BIM, digital twins, AR/VR, robotics, etc.) are applied across the electrical construction lifecycle: preconstruction planning, site execution, and closeout / operations & maintenance. Maturity is rated Conceptual, Lab-validated, or Field-tested.

You have been retrieved a small set of relevant papers in two tiers:

PRIMARY SOURCES [1]–[${cited.length}] — the most relevant papers with full context. Cite these directly using [1], [2], [3]. These are your main evidence.

SUPPORTING SOURCES [${cited.length + 1}]–[${cited.length + mentioned.length}] — additional relevant papers in compact form. Cite only when they add something primary sources do not cover.

Rules:
1. Provide a COMPLETE answer. Do not stop mid-sentence.
2. For "what/how" questions: 2–4 sentences, direct answer.
3. For analytical questions (gaps, comparisons, trends): brief overview + 2–4 specific findings grounded in cited papers + a closing observation.
4. Cite EVERY substantive claim with a bracketed number. Multiple papers: [1, 2].
5. Lean heavily on PRIMARY SOURCES. Use SUPPORTING SOURCES only for unique evidence not already covered.
6. If retrieved papers don't have enough information, say so explicitly. Do not hallucinate.
7. Plain academic prose. No markdown bold or headers. No bullet points unless explicitly requested.

PRIMARY SOURCES:

${citedBlock}

SUPPORTING SOURCES:

${mentionedBlock}`;

    const contents = [];
    if (history.length === 0) {
      contents.push({ role: 'user', parts: [{ text: systemCtx + '\n\nUSER QUESTION: ' + question }] });
    } else {
      history.forEach(m => contents.push({ role: m.role, parts: [{ text: m.text }] }));
      contents.push({ role: 'user', parts: [{ text: systemCtx + '\n\nUSER QUESTION: ' + question }] });
    }

    const url = workerBase
      ? `${workerBase}/api/generate`
      : `${GEMINI_GENERATE_URL}?key=${encodeURIComponent(apiKey)}`;
    const res = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents,
        generationConfig: { temperature: 0.3, maxOutputTokens: 4096 },
      }),
    });
    if (!res.ok) {
      const t = await res.text();
      throw new Error(`Generation error (${res.status}): ${t.slice(0, 200)}`);
    }
    const data = await res.json();
    const text = data?.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!text) throw new Error('Gemini returned no content — the prompt may have been blocked.');
    return text;
  };

  // ── Main component ────────────────────────────────────
  const AIChat = ({ rows, workerBase, apiKey, onPaperClick }) => {
    const [embeddings,       setEmbeddings]       = useState(null);
    const [embeddingLoading, setEmbeddingLoading] = useState(true);
    const [embeddingError,   setEmbeddingError]   = useState(null);
    const [messages,  setMessages]  = useState([]);
    const [question,  setQuestion]  = useState('');
    const [loading,   setLoading]   = useState(false);
    const [error,     setError]     = useState(null);
    const messagesEndRef = useRef(null);

    // Load pre-computed embeddings JSON
    useEffect(() => {
      let cancelled = false;
      fetch('./paper_embeddings.json')
        .then(r => {
          if (!r.ok) throw new Error(`HTTP ${r.status} — file not found`);
          return r.json();
        })
        .then(data => { if (!cancelled) { setEmbeddings(data); setEmbeddingLoading(false); } })
        .catch(err => { if (!cancelled) { setEmbeddingError(err.message); setEmbeddingLoading(false); } });
      return () => { cancelled = true; };
    }, []);

    // Auto-scroll on new message
    useEffect(() => {
      messagesEndRef.current?.scrollIntoView({ behavior: 'smooth', block: 'end' });
    }, [messages, loading]);

    // Fast paper lookup by ID (string-coerced)
    const paperById = useMemo(() => {
      const m = new Map();
      rows.forEach(p => m.set(String(p.ID), p));
      return m;
    }, [rows]);

    const apiConfigured = !!workerBase || (apiKey && apiKey !== 'YOUR_API_KEY_HERE' && apiKey.length > 10);

    // ── Submit handler ──────────────────────────────────
    const submit = async () => {
      const q = question.trim();
      if (!q || loading || !apiConfigured || !embeddings) {
        if (!apiConfigured) setError('AI Assistant not configured. Set GEMINI_WORKER_BASE or GEMINI_API_KEY in app.js.');
        if (!embeddings && !embeddingLoading) setError('paper_embeddings.json not found. Run compute_embeddings.py first.');
        return;
      }
      setError(null);
      setQuestion('');
      setLoading(true);
      setMessages(prev => [...prev, { role: 'user', text: q }]);

      try {
        // 1. Embed question
        const qVec = await embedQuestion(workerBase, apiKey, q);
        if (!qVec?.length) throw new Error('Embedding API returned empty vector.');

        // 2. Rank papers by cosine similarity
        const scored = embeddings.papers
          .map(p => ({ ...p, score: cosineSim(qVec, p.embedding) }))
          .sort((a, b) => b.score - a.score);

        const rawCited     = scored.slice(0, CITED_K);
        const rawMentioned = scored.slice(CITED_K, CITED_K + MENTIONED_K);
        const rawFurther   = scored.slice(CITED_K + MENTIONED_K, TOP_K);

        // 3. APA disambiguation (when two papers share citation string in same set)
        const all = [...rawCited, ...rawMentioned, ...rawFurther];
        const citCount = new Map();
        all.forEach(p => {
          if (!citCount.has(p.citation)) citCount.set(p.citation, new Set());
          citCount.get(p.citation).add(String(p.id));
        });
        const disambig = new Map();
        citCount.forEach((ids, cit) => {
          if (ids.size > 1) {
            const ordered = [];
            all.forEach(p => { if (p.citation === cit && !ordered.includes(String(p.id))) ordered.push(String(p.id)); });
            ordered.forEach((pid, i) => {
              disambig.set(pid, cit.replace(/\((\d{4})\)/, `($1${String.fromCharCode(97 + i)})`));
            });
          }
        });
        const applyD = arr => arr.map(p => {
          const c = disambig.get(String(p.id));
          return c ? { ...p, citation: c } : p;
        });
        const cited     = applyD(rawCited);
        const mentioned = applyD(rawMentioned);
        const further   = applyD(rawFurther);

        // 4. Generate answer with conversation history
        const history = messages.map(m => ({ role: m.role === 'user' ? 'user' : 'model', text: m.text }));
        const answer = await askGemini(workerBase, apiKey, q, cited, mentioned, history);

        // 5. Build unified retrieved list
        const retrieved = [
          ...cited.map((p, i) => ({
            idx: i + 1, tier: 'cited', id: p.id,
            citation: p.citation, title: p.summary?.title || '', score: p.score,
          })),
          ...mentioned.map((p, i) => ({
            idx: CITED_K + i + 1, tier: 'mentioned', id: p.id,
            citation: p.citation, title: p.summary?.title || '', score: p.score,
          })),
          ...further.map(p => ({
            idx: null, tier: 'further', id: p.id,
            citation: p.citation, title: p.summary?.title || '', score: p.score,
          })),
        ];

        setMessages(prev => [...prev, { role: 'assistant', text: answer, retrieved }]);
      } catch (e) {
        setError(e.message || String(e));
      } finally {
        setLoading(false);
      }
    };

    const reset = () => { setMessages([]); setError(null); setQuestion(''); };

    // ── Render answer with clickable citation chips ─────
    const renderAnswer = (text, retrieved) => {
      if (!retrieved) return <span>{text}</span>;
      const clean = text.replace(/\*\*(.+?)\*\*/g, '$1');
      const byIdx = new Map(retrieved.filter(r => r.idx != null).map(r => [r.idx, r]));
      return (
        <>
          {clean.split(/\n\n+/).map((para, pi) => {
            const parts = [];
            const re = /\[(\d+(?:\s*,\s*\d+)*)\]/g;
            let last = 0, m, k = 0;
            while ((m = re.exec(para)) !== null) {
              if (m.index > last) parts.push(<span key={k++}>{para.slice(last, m.index)}</span>);
              const idxs = m[1].split(',').map(s => parseInt(s.trim()));
              parts.push(
                <span key={k++} className="inline-flex flex-wrap gap-0.5 items-baseline">
                  {idxs.map((idx, j) => {
                    const r = byIdx.get(idx);
                    if (!r) return <span key={j}>[{idx}]</span>;
                    const paper = paperById.get(String(r.id));
                    return (
                      <button key={j}
                        onClick={() => paper && onPaperClick && onPaperClick(paper)}
                        title={`${r.citation} — ${r.title}`}
                        className="text-[10px] font-semibold text-slate-700 bg-slate-100 hover:bg-slate-900 hover:text-white border border-slate-300 px-1 py-px rounded transition-colors align-baseline"
                      >
                        {idx}
                      </button>
                    );
                  })}
                </span>
              );
              last = re.lastIndex;
            }
            if (last < para.length) parts.push(<span key={k++}>{para.slice(last)}</span>);
            return <p key={pi} className={pi > 0 ? 'mt-3' : ''}>{parts}</p>;
          })}
        </>
      );
    };

    // ── Loading / error states ────────────────────────
    if (embeddingLoading) return (
      <div className="bg-white border border-slate-200 rounded-lg p-10 text-center">
        <div className="inline-block w-5 h-5 border-2 border-slate-300 border-t-slate-700 rounded-full animate-spin mb-3"></div>
        <p className="text-sm text-slate-600">Loading paper embeddings…</p>
      </div>
    );

    if (embeddingError) return (
      <div className="bg-amber-50 border border-amber-200 rounded-lg p-6">
        <div className="font-semibold text-amber-900 mb-2">Embeddings file not found</div>
        <p className="text-xs text-amber-800 leading-relaxed mb-3">
          The AI assistant needs <code className="bg-amber-100 px-1 rounded">paper_embeddings.json</code> in the
          same folder as <code className="bg-amber-100 px-1 rounded">index.html</code>.
          Generate it once by running:
        </p>
        <pre className="bg-white border border-amber-200 rounded p-3 text-[11px] text-amber-900 overflow-x-auto">pip install google-genai pandas{'\n'}python compute_embeddings.py</pre>
        <p className="text-[11px] text-amber-700 mt-2">Error: {embeddingError}</p>
      </div>
    );

    // ── Example questions ─────────────────────────────
    const examples = [
      'Which AI techniques are most underexplored for electrical installation?',
      'What field-tested studies exist on BIM for electrical coordination?',
      'How is computer vision being used on electrical construction sites?',
      'Which papers address prefabrication and off-site electrical work?',
      'What are the main gaps in safety research for electrical workers?',
      'Which studies compare AR and VR for electrical training?',
    ];

    return (
      <div className="space-y-4">
        {/* API not configured warning */}
        {!apiConfigured && (
          <div className="bg-amber-50 border border-amber-200 rounded-lg p-4 text-sm text-amber-900">
            <div className="font-semibold mb-1">AI Assistant not configured</div>
            <div className="text-xs leading-relaxed">
              For production: set <code className="bg-amber-100 px-1 rounded">GEMINI_WORKER_BASE</code> in <code className="bg-amber-100 px-1 rounded">app.js</code> to your Cloudflare Worker URL.{' '}
              For local testing: set <code className="bg-amber-100 px-1 rounded">GEMINI_API_KEY</code> in the same file.
            </div>
          </div>
        )}

        {/* Main chat card */}
        <div className="bg-white border border-slate-200 rounded-lg p-5">
          <div className="flex items-baseline justify-between gap-3 mb-4">
            <div>
              <h3 className="serif text-lg font-semibold text-slate-900">Ask the reviewed literature</h3>
              <p className="text-xs text-slate-500 mt-0.5">
                Top {CITED_K} most relevant papers become primary citations · {MENTIONED_K} become supporting references · {FURTHER_K} surface as further reading · {embeddings?.n_papers || 0} papers indexed
              </p>
            </div>
            {messages.length > 0 && (
              <button onClick={reset} className="text-xs text-slate-500 hover:text-slate-900 underline flex-shrink-0">
                Clear
              </button>
            )}
          </div>

          {/* Conversation thread */}
          {messages.length > 0 && (
            <div className="space-y-3 mb-4 max-h-[60vh] overflow-y-auto scrollbar-thin pr-1">
              {messages.map((m, i) => (
                <div key={i} className="animate-fade">
                  {m.role === 'user' ? (
                    <div className="flex justify-end">
                      <div className="bg-slate-900 text-white px-4 py-2 rounded-lg max-w-[85%] text-sm leading-relaxed">
                        {m.text}
                      </div>
                    </div>
                  ) : (
                    <div className="space-y-2">
                      {/* Answer text */}
                      <div className="bg-slate-50 border border-slate-200 px-4 py-3 rounded-lg text-sm text-slate-800 serif leading-relaxed">
                        {renderAnswer(m.text, m.retrieved)}
                      </div>

                      {/* References */}
                      {m.retrieved && (() => {
                        const refs    = m.retrieved.filter(r => r.tier !== 'further');
                        const further = m.retrieved.filter(r => r.tier === 'further');
                        return (
                          <div className="space-y-2 text-xs">
                            {refs.length > 0 && (
                              <div>
                                <div className="text-[10px] uppercase tracking-wider font-semibold text-slate-500 mb-1.5 px-1">
                                  References ({refs.length})
                                </div>
                                <div className="space-y-1">
                                  {refs.map(r => {
                                    const paper = paperById.get(String(r.id));
                                    const isPrimary = r.tier === 'cited';
                                    return (
                                      <button key={r.idx}
                                        onClick={() => paper && onPaperClick && onPaperClick(paper)}
                                        className={`block w-full text-left p-2 border rounded transition-colors ${
                                          isPrimary
                                            ? 'bg-white border-slate-300 hover:border-slate-500 hover:shadow-sm'
                                            : 'bg-slate-50 border-slate-200 hover:bg-white hover:border-slate-400'
                                        }`}
                                      >
                                        <div className="flex items-baseline gap-2">
                                          <span className={`font-mono flex-shrink-0 ${isPrimary ? 'text-slate-700 font-semibold' : 'text-slate-400'}`}>
                                            [{r.idx}]
                                          </span>
                                          <div className="min-w-0 flex-1">
                                            <div className="flex items-baseline gap-2 flex-wrap">
                                              <span className="font-medium text-slate-800">{r.citation}</span>
                                              {isPrimary && (
                                                <span className="text-[9px] uppercase tracking-wider font-semibold text-emerald-700 bg-emerald-50 border border-emerald-200 px-1 py-px rounded">
                                                  primary
                                                </span>
                                              )}
                                            </div>
                                            <div className="text-slate-500 text-[11px] leading-snug">{r.title}</div>
                                          </div>
                                          <span className="text-[10px] text-slate-400 tabular-nums flex-shrink-0">
                                            {(r.score * 100).toFixed(0)}%
                                          </span>
                                        </div>
                                      </button>
                                    );
                                  })}
                                </div>
                              </div>
                            )}

                            {/* Further reading (collapsed) */}
                            {further.length > 0 && (
                              <details className="pt-1">
                                <summary className="cursor-pointer text-[11px] text-slate-500 hover:text-slate-900 px-1 py-1">
                                  Further reading ({further.length}) — related papers you may want to explore
                                </summary>
                                <div className="mt-2 space-y-1">
                                  {further.map((r, i) => {
                                    const paper = paperById.get(String(r.id));
                                    return (
                                      <button key={i}
                                        onClick={() => paper && onPaperClick && onPaperClick(paper)}
                                        className="block w-full text-left p-2 bg-white border border-dashed border-slate-200 rounded hover:border-slate-400 hover:bg-slate-50 transition-colors"
                                      >
                                        <div className="flex items-baseline gap-2">
                                          <span className="text-slate-300 flex-shrink-0">•</span>
                                          <div className="min-w-0 flex-1">
                                            <div className="font-medium text-slate-700">{r.citation}</div>
                                            <div className="text-slate-500 text-[11px] leading-snug">{r.title}</div>
                                          </div>
                                          <span className="text-[10px] text-slate-400 tabular-nums flex-shrink-0">
                                            {(r.score * 100).toFixed(0)}%
                                          </span>
                                        </div>
                                      </button>
                                    );
                                  })}
                                </div>
                              </details>
                            )}
                          </div>
                        );
                      })()}
                    </div>
                  )}
                </div>
              ))}

              {/* Thinking indicator */}
              {loading && (
                <div className="bg-slate-50 border border-slate-200 px-4 py-3 rounded-lg text-sm text-slate-500 italic flex items-center gap-2">
                  <div className="w-3 h-3 border border-slate-300 border-t-slate-700 rounded-full animate-spin"></div>
                  Searching the reviewed papers and generating answer…
                </div>
              )}
              <div ref={messagesEndRef} />
            </div>
          )}

          {/* Example questions (only before first message) */}
          {messages.length === 0 && (
            <div className="mb-4">
              <div className="text-[10px] uppercase tracking-wider font-semibold text-slate-500 mb-2">
                Try one of these
              </div>
              <div className="flex flex-wrap gap-1.5">
                {examples.map((eq, i) => (
                  <button key={i} onClick={() => setQuestion(eq)}
                    className="text-xs text-left bg-white border border-slate-200 hover:border-slate-400 hover:bg-slate-50 rounded px-2.5 py-1.5 text-slate-700 transition-colors">
                    {eq}
                  </button>
                ))}
              </div>
            </div>
          )}

          {/* Input */}
          <div className="flex gap-2 items-end">
            <textarea
              value={question}
              onChange={e => setQuestion(e.target.value)}
              onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); submit(); } }}
              placeholder={messages.length === 0
                ? `Ask anything about the ${rows.length} reviewed papers…`
                : 'Follow up…'}
              rows={2}
              disabled={loading || !apiConfigured}
              className="flex-1 px-3 py-2 text-sm border border-slate-200 rounded-md focus:outline-none focus:border-slate-900 focus:ring-1 focus:ring-slate-900 resize-none"
            />
            <button
              onClick={submit}
              disabled={loading || !question.trim() || !apiConfigured}
              className="px-4 py-2 text-sm font-medium bg-slate-900 text-white rounded-md hover:bg-slate-800 transition-colors disabled:bg-slate-300 disabled:cursor-not-allowed"
            >
              Ask
            </button>
          </div>
          <div className="text-[10px] text-slate-400 mt-2">
            Enter to send · Shift+Enter for new line · AI-generated answers may contain errors — verify against cited papers.
          </div>
        </div>

        {/* Error banner */}
        {error && (
          <div className="bg-red-50 border border-red-200 rounded-lg p-3 text-xs text-red-900">
            <span className="font-semibold">Error: </span>
            <span className="font-mono break-words">{error}</span>
          </div>
        )}
      </div>
    );
  };

  window.AppCharts.AIChat = AIChat;
})();
